# Đổi cổng sang 1195
port 1195
proto udp
dev tun
topology subnet

# Trỏ đến thư mục khóa mới
ca /etc/openvpn/server_ecdsa/ca.crt
cert /etc/openvpn/server_ecdsa/server.crt
key /etc/openvpn/server_ecdsa/server.key
tls-auth /etc/openvpn/server_ecdsa/ta.key 0

dh none

# Dải IP hoàn toàn mới cho mạng ECDSA
server 10.9.0.0 255.255.255.0
keepalive 10 120

cipher AES-256-GCM
auth SHA256
tls-version-min 1.2

user nobody
group nogroup

persist-key
persist-tun
# Đổi tên file log để không ghi đè log cũ
status /var/log/openvpn/server_ecdsa.status 1
verb 3

# Báo cho máy Windows biết dải mạng nội bộ (ví dụ 192.168.1.0) nằm sau VPN
push "route 192.168.1.0 255.255.255.0"

script-security 2
client-connect /etc/openvpn/remote_trigger.sh
client-disconnect /etc/openvpn/remote_untouch.sh
